### ISSUE TITLE
Replace old links

### ISSUE THREAD

**Issue by daniel-farina** [PrintM3D/Promega-Docs#3]
@flipthedog 
There are some links that need to be updated before we make the official switch tomorrow.  Use [this search ](https://github.com/PrintM3D/Promega-Docs/search?q=http%3A%2F%2Fpromega.printm3d.com%2Fbooks&unscoped_q=http%3A%2F%2Fpromega.printm3d.com%2Fbooks&type=Code)

**Comment by flipthedog** [comment]
**Fixed!**
