### ISSUE TITLE
Z-Level doc mentions IR probe, but no instructions on how to use

### ISSUE THREAD

**Issue by zorrobyte** [PrintM3D/Promega-Docs#9]
https://github.com/PrintM3D/Promega-Docs/blob/master/getting-started/z-probe-calibration-and-bed-leveling.md

The docs say, "The Promega comes equipped with two different Z-probes, the limit switch and the IR probe. This guide can be followed to configure either one." -- https://promega.printm3d.com/getting-started/z-probe-calibration-and-bed-leveling But doesn't have instructions on how to actually switch to the IR probe.

Why are there two probes? Is one more effective than the other?

**Comment by TheBum** [comment]
The IR probe was the original plan, but it doesn’t work well when using a glass sheet. The limit switch was added more or less at the last minute to address that.

**Comment by zorrobyte** [comment]
My printer came with a buildtak sheet, like many others. Maybe it’ll be
worth documenting anyway. I’ll try to write something up soon if I can find
the Duet docs explaining it.

**Comment by zorrobyte** [comment]
Which sensor does the Promega use?
https://duet3d.dozuki.com/Wiki/Connecting_a_Z_probe
